import java.io.File;
import java.io.FileInputStream;

// Reads file and creates an array of strings, each string representing a line from the source file
public class Reader {

    private String[] assemblyUnit;

    public Reader(String filename) throws Exception {

        //Open the source file
        File srcFile = new File(filename);
        if (!srcFile.canRead()) {
            System.out.println("Unable to open source file '" + filename + "'");
            return;
        }

        //Read the source file using FileInputStream
        FileInputStream file = new FileInputStream(srcFile);

        //Traverse the contents of the source file and save them to fileContent
        String fileContent = "";
        int currentChar = file.read();
        while(currentChar > 0) {
            fileContent += (char)currentChar;
            currentChar = file.read();
        }

        //Close the source file
        file.close();

        //Create an assembly unit comprised of unparsed line statements using EOL
        assemblyUnit = fileContent.split("[\r\n]+");
    }

    //Get the assembly unit generated by FileReader
    public String[] getAssemblyUnit() {
        return assemblyUnit;
    }
}
